### ISSUE TITLE
Add update Button/Notification

### ISSUE THREAD

**Issue by shaphir** [lfuelling/lrkFM#18]
Hello sir, I have a little advice on this project. Add it feature Update this app will greatly help the user, it's very difficult to check this app in the playstore, it will not even be visible when I type it in search.

Given this new feature will make it easier for users, if this app has upgraded to the latest version. Users can use this shortcut to update it.

As an example I've edited
![picsart_05-18-10 32 11](https://user-images.githubusercontent.com/38022258/40244195-6b053510-5aec-11e8-8bbe-a4fc7bb31005.jpg)

**Comment by shaphir** [comment]
apologize for my chaotic english 😑

**Comment by lfuelling** [comment]
Hi,

thanks for the feedback. And don't worry about your english, if I don't get something, I'll ask. 😄 

Unfortunately I have exactly the same hard time finding the app in the PlayStore. I could suggest that you use "My purchases and updates" in the PlayStore menu to check for updates or switch on automatic updates.

The problem with the update button is checking if a new version is available because the PlayStore takes a few hours to do checks on the application before the update is visible.

I will think about possible solutions for this problem and come back to this issue when I came up with a solution.

**Comment by shaphir** [comment]
Hehe, glad to help you sir.
I thinking of waiting some questions from you, (only if I can answer them) 😁

**Comment by lfuelling** [comment]
I made it so that the check is only done once the app is launched. 

I had an app once that notified me about an update when it was not running and I thought that was kind of spammy so I won't implement this.
